# Generated by Django 3.2.2 on 2021-07-26 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_keluar', '0002_auto_20210722_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkeluar',
            name='penerima',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productkeluar',
            name='category',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productkeluar',
            name='product',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
