# Generated by Django 3.2.2 on 2021-07-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_keluar', '0003_auto_20210726_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkeluar',
            name='penerima',
        ),
    ]
