# Generated by Django 3.2.2 on 2021-07-31 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_keluar', '0004_remove_productkeluar_penerima'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkeluar',
            name='satuan',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
