# Generated by Django 3.2.2 on 2021-07-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_masuk', '0003_rename_name_supp_productmasuk_name_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmasuk',
            old_name='name',
            new_name='name_bahan',
        ),
    ]
