# Generated by Django 3.2.2 on 2021-07-31 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_masuk', '0006_alter_productmasuk_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmasuk',
            name='satuan',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
