# Generated by Django 3.2.2 on 2021-07-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_cust_kode'),
        ('orders', '0004_rename_cust_id_order_cust_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust_kode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kode', to='customer.customer'),
        ),
    ]
