# Generated by Django 3.2.2 on 2021-07-23 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_cust_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tanggal',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%d %H:%M:%S'),
            preserve_default=False,
        ),
    ]
