# Generated by Django 3.2.2 on 2021-07-23 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tanggal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 23, 21, 27, 57, 608218)),
        ),
    ]
