# Generated by Django 3.2.2 on 2021-07-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
