# Generated by Django 3.2.2 on 2021-07-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_tanggal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cust_kode',
        ),
    ]
