# Generated by Django 3.2.2 on 2021-07-26 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_cust_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kode_transaksi',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
